const semanticString = {
  effectType: {
    overdrive: '오버드라이브',
    distortion: '디스토션',
    fuzz: '퍼즈',
    boost: '부스터',
    chorus: '코러스',
    flanger: '플랜저',
    phaser: '페이저',
    tremolo: '트레몰로',
    vibrato: '비브라토',
    rotarySpeaker: '로터리 스피커',
    delay: '딜레이',
    reverb: '리버브',
    compressor: '컴프레서',
    sustainer: '서스테이너',
    limiter: '리미터',
    noiseGate: '노이즈 게이트',
    equalizer: '이퀄라이저',
    wah: '와우',
    envelopeFilter: '엔벨롭 필터',
    preamp: '프리앰프',
    pitchShifter: '피치 쉬프터',
    octaver: '옥타버',
    harmonizer: '하모나이저',
    tuner: '튜너',
    looper: '루퍼',
    volumePedal: '볼륨 페달',
    expressionPedal: '익스프레션 페달',
    switcher: '스위처',
    simulator: '시뮬레이터',
    multiEffects: '멀티이펙터',
    ringModulator: '링 모듈레이터',
    talkbox: '토크박스',
    signalBuffer: '시그널 버퍼',
    powerSupply: '파워 서플라이',
    pedalboard: '페달보드',
    patchCable: '패치케이블',
  },
  condition: {
    brandNew: '신품',
    mint: '매우 양호',
    good: '양호',
    fair: '보통',
    poor: '하자/고장',
  },
  time: {
    justNow: '방금 전',
    minuteAgo: '분 전',
    hourAgo: '시간 전',
    dayAgo: '일 전',
  },
  string: {
    searchPlaceholder: '어떤 악기를 찾고 있나요?',
  },
  BrandMap: {
    '1981 Inventions': 1,
    '29 Pedals': 2,
    '3Degrees Audio': 3,
    '3Leaf Audio': 4,
    '3rd Power': 5,
    'A/DA': 6,
    'A3 Stompboxes': 7,
    AAA: 8,
    'AC Noises': 9,
    AMT: 10,
    API: 11,
    AVTPedals: 12,
    Abasi: 13,
    Aclam: 14,
  },
  EffectMap: {
    오버드라이브: 1,
    디스토션: 2,
    퍼즈: 3,
    부스터: 4,
    코러스: 5,
    플랜저: 6,
    페이저: 7,
    트레몰로: 8,
    비브라토: 9,
    '로터리 스피커': 10,
    딜레이: 11,
    리버브: 12,
    컴프레서: 13,
    서스테이너: 14,
    리미터: 15,
    '노이즈 게이트': 16,
    이퀄라이저: 17,
    와우: 18,
    '엔벨롭 필터': 19,
    프리앰프: 20,
    '피치 쉬프터': 21,
    옥타버: 22,
    하모나이저: 23,
    튜너: 24,
    루퍼: 25,
    '볼륨 페달': 26,
    '익스프레션 페달': 27,
    스위처: 28,
    시뮬레이터: 29,
    멀티이펙터: 30,
    '링 모듈레이터': 31,
    토크박스: 32,
    '시그널 버퍼': 33,
    '파워 서플라이': 34,
    '드럼 머신': 35,
    미디: 36,
    신디사이저: 37,
  },
};

export { semanticString };
